name: Server Workflows

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ROOT_PASS: ${{ secrets.ROOT_PASS }}
      ZROK_ENV: ${{ secrets.ZROK_ENV }}

    steps:
    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg xrdp curl p7zip-full

    - name: Download zrok
      run: |
        wget https://github.com/openziti/zrok/releases/download/v0.4.24/zrok_0.4.24_linux_amd64.tar.gz -O zrok.tar.gz

    - name: Install zrok
      run: |
        mkdir /tmp/zrok && tar -xf ./zrok.tar.gz -C /tmp/zrok
        mkdir -p ~/bin && install /tmp/zrok/zrok ~/bin/
        echo 'export PATH=~/bin:$PATH' >> ~/.bashrc
        source ~/.bashrc  # Update the current session
        
    - name: Configure Remote Desktop and Change Root Password
      run: |
        echo "root:$ROOT_PASS" | sudo chpasswd
        sudo systemctl enable xrdp
        sudo systemctl start xrdp
        sudo ufw allow 3389/tcp

    - name: Tunnel Setup with zrok
      run: |
        ls
        pwd
        zrok enable "$ZROK_ENV"
        zrok share private --backend-mode tcpTunnel 127.0.0.1:3389
