name: Server Workflows

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ROOT_PASS: ${{ secrets.ROOT_PASS }}
      ZROK_ENV: ${{ secrets.ZROK_ENV }}

    steps:
    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg xrdp curl p7zip-full

    - name: Install zrok
      run: |
        curl -sSLfo ./zrok-install.bash https://get.openziti.io/install.bash
        less ./zrok-install.bash  # Optional: Inspect script for security
        sudo bash ./zrok-install.bash zrok

    - name: Configure Remote Desktop and Change Root Password
      run: |
        echo "root:$ROOT_PASS" | sudo chpasswd
        sudo systemctl enable xrdp
        sudo systemctl start xrdp
        sudo ufw allow 3389/tcp

    - name: Tunnel Setup with zrok
      run: |
        ls
        pwd
        zrok enable "$ZROK_ENV"
        zrok share private --backend-mode tcpTunnel 127.0.0.1:3389
