name: Server Workflows

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ROOT_PASS: ${{ secrets.ROOT_PASS }}
      ZROK_ENV: ${{ secrets.ZROK_ENV }}

    steps:
    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg xrdp curl p7zip-full expect screen

    - name: Download zrok
      run: |
        wget https://github.com/openziti/zrok/releases/download/v0.4.24/zrok_0.4.24_linux_amd64.tar.gz -O zrok.tar.gz

    - name: Install zrok
      run: |
        mkdir ./zrok && tar -xf ./zrok.tar.gz -C ./zrok
        ./zrok/zrok version

    - name: Configure Remote Desktop and Change Root Password
      run: |
        echo "root:$ROOT_PASS" | sudo chpasswd
        sudo systemctl enable xrdp
        sudo systemctl start xrdp
        sudo ufw allow 3389/tcp

    - name: Folder Check
      run: |
        ls
        pwd

    - name: Tunnel Setup with zrok
      run: |
        ls
        pwd
        export TERM=dumb  # Set TERM to avoid TTY issues
        screen -L -dm bash -c "./zrok/zrok enable '$ZROK_ENV' > zrok_enable.log 2>&1"
        screen -L -dm bash -c "./zrok/zrok share private --backend-mode tcpTunnel 127.0.0.1:3389 > zrok_share.log 2>&1"

    - name: Check zrok output
      run: |
        sleep 10
        echo "Output from zrok enable:"
        cat zrok_enable.log
        echo "-------------------------------------"
        echo "Output from zrok share:"
        cat zrok_share.log
        sleep 21600
